# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://ftp.crm.gpaudax.com.br'
    username: 'crm'
    password: '4PxUDaGZ'
    rootDirectory: '$(Build.ArtifactStagingDirectory)' # Ou o diretório onde seus artefatos de build estão localizados
    filePatterns: '**' # Isso especifica que todos os arquivos e diretórios devem ser carregados
    remoteDirectory: '/www' # Caminho no servidor FTP onde os arquivos devem ser colocados
    clean: false
    preservePaths: true